[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "go"
language-servers = [ "gopls", "golangci-lint-lsp", "gpt" ]
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]

[language-server.ltex-ls.config]
ltex.languageToolHttpServerUri = "http://localhost:8081/"

[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "copilot"]
